name: webdav
services:
  webdav:
    environment:
      USERNAME: admin
      PASSWORD: admin1234
    image: derkades/webdav:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "8081"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - /DATA:/data
    container_name: webdav

x-casaos:
  id: com.cp0204.webdav
  architectures:
    - amd64
    - arm64
  main: webdav
  store_app_id: webdav
  author: bytemark
  category: Productivity
  description:
    en_US: A simple WebDAV server.
    zh_CN: 一个简单的WebDAV服务器。
  developer: bytemark
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/webdav/icon.png
  tagline:
    en_US: Simple WebDAV Server
    zh_CN: 简单的WebDAV服务器
  tips:
    before_install:
      en_US: 'Default username: `admin`, default password: `admin1234`'
      zh_CN: '默认用户名：`admin` ，默认密码：`admin1234`'
  title:
    en_US: WebDAV
  index: /
  port_map: "8081"
