name: samba
services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    environment:
      NAME: "Data"
      USER: "admin"
      PASS: "password"
      RW: "true"
    ports:
      - "445:445"
    volumes:
      - /DATA:/storage
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge

x-casaos:
  id: com.cp0204.samba
  architectures:
    - arm
    - arm64
    - amd64
  main: samba
  store_app_id: samba
  author: Cp0204
  category: Productivity
  description:
    en_US: Samba SMB server in a Docker container. An implementation of the Windows SMB networking protocol, allowing file sharing between Windows, Linux and macOS systems. [DOC](https://hub.docker.com/r/dockurr/samba)
    zh_CN: Docker 容器中的 Samba SMB 服务器。可以加密码🙃，实现了Windows SMB网络协议，允许在Windows、Linux和macOS系统之间共享文件。[文档](https://hub.docker.com/r/dockurr/samba)
  developer: dockurr
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/samba/icon.png
  tagline:
    en_US: Share files across all your devices with SMB protocol
    zh_CN: 使用SMB协议在所有设备间共享文件
  tips:
    before_install:
      en_US: You need to disable the SMB service that comes with the system first to free up port 445, refer to the command `systemctl stop smb && systemctl disable smb`. Default username is `admin` and password is `password`. Please change these credentials after installation for security.
      zh_CN: 需要先把系统自带的SMB服务禁用，以释放445端口，参考命令`systemctl stop smb && systemctl disable smb`，默认用户名为`admin`，密码为`password`。出于安全考虑，安装后请更改这些凭据。
  title:
    en_US: Samba
    zh_CN: SMB共享
  index: /
  port_map: "445"
