name: sscms
services:
  sscms:
    image: sscms/core:latest
    container_name: sscms
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - /DATA/AppData/sscms/wwwroot:/app/wwwroot
    environment:
      SSCMS_SECURITY_KEY: e2a3d303-ac9b-41ff-9154-930710af0845
      SSCMS_DATABASE_TYPE: SQLite
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  main: sscms
  store_app_id: sscms
  author: Cp0204
  category: WEB
  description:
    en_us: SiteServer CMS is an open-source, free, enterprise-grade, and commercially available CMS content management system. It allows you to build a full-featured, high-performance, large-scale, and easy-to-maintain website platform with minimal cost, manpower, and time.
    zh_cn: SiteServer CMS是一款开源免费、企业级、可商用的CMS内容管理系统，能够以最低的成本、最少的人力投入在最短的时间内架设一个功能齐全、性能优异、规模庞大并易于维护的网站平台。
  developer: sscms.com
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/sscms/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/sscms/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/sscms/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/sscms/screenshot-3.png
  tagline:
    en_us: Open-source, free, and enterprise-grade CMS
    zh_cn: 开源免费企业级CMS
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/sscms/thumbnail.png
  title:
    en_us: SiteServer CMS
    zh_cn: SiteServer CMS
  index: /ss-admin/install
  port_map: "8081"