name: rustdesk-server
services:
  hbbs:
    command:
      - hbbs
    container_name: rustdesk-server-hbbs
    depends_on:
      - hbbr
    image: rustdesk/rustdesk-server:latest
    environment:
      - KEY=YOURKEY # 如果设置了此参数，将强制使用指定密钥对，如果设为 "_"，则强制使用任意密钥；下同
    restart: unless-stopped
    volumes:
      - /DATA/AppData/rustdesk-server/data:/root
    networks:
      - rustdesk-server
    network_mode: bridge
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118

  hbbr:
    command:
      - hbbr
    container_name: rustdesk-server-hbbr
    image: rustdesk/rustdesk-server:latest
    environment:
      - KEY=YOURKEY
    restart: unless-stopped
    volumes:
      - /DATA/AppData/rustdesk-server/data:/root
    networks:
      - rustdesk-server
    network_mode: bridge
    ports:
      - 21117:21117
      - 21119:21119

  api:
    image: lejianwen/rustdesk-api:latest
    container_name: rustdesk-server-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_APP_REGISTER=true
      - RUSTDESK_API_LANG=zh-CN
      - RUSTDESK_API_RUSTDESK_ID_SERVER=192.168.1.66:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=192.168.1.66:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://192.168.1.66:21114
      - RUSTDESK_API_RUSTDESK_KEY=YOURKEY
    network_mode: bridge
    ports:
      - 21114:21114
    volumes:
      - /DATA/AppData/rustdesk-server/api:/app/data
    networks:
      - rustdesk-server
    restart: unless-stopped
    depends_on:
      - hbbs
      - hbbr

networks:
  rustdesk-server:
    external: false
    name: rustdesk-server

x-casaos:
  architectures:
    - arm
    - arm64
    - amd64
  main: api
  store_app_id: rustdesk-server
  category: Utilities
  author: Cp0204
  developer: rustdesk | lejianwen
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/rustdesk-server/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/rustdesk-server/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/rustdesk-server/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/rustdesk-server/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/rustdesk-server/thumbnail.png
  description:
    en_us: RustDesk builds its own transit server, combining the official [rustdesk-server](https://github.com/rustdesk/rustdesk-server) and lejianwen's [rustdesk-api](https://github.com/lejianwen/rustdesk-api).
    zh_cn: RustDesk 自建中转服务器，集合官方 [rustdesk-server](https://github.com/rustdesk/rustdesk-server) 与 lejianwen 的 [rustdesk-api](https://github.com/lejianwen/rustdesk-api) 服务。
  tagline:
    en_us: RustDesk Self-Hosted
    zh_cn: RustDesk 自托管
  title:
    en_us: RustDesk Server
  tips:
    before_install:
      en_us: The initial installation administrator is the username admin, the password will be printed on the console, you can change the password via [CLI](https://github.com/lejianwen/rustdesk-api#CLI)
      zh_cn: 初次安装管理员为用户名为admin，密码将在控制台打印，可以通过[命令行](https://github.com/lejianwen/rustdesk-api#CLI)更改密码
  port_map: "21114"
  scheme: http
  index: /
