name: beancount-gs
services:
  beancount-gs:
    container_name: beancount-gs
    image: xdbin/beancount-gs:latest
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
      - target: 80
        published: "10000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/beancount
        target: /data/beancount
      - type: bind
        source: /DATA/AppData/beancount/icons
        target: /app/public/icons
      - type: bind
        source: /DATA/AppData/beancount/config
        target: /app/config
      - type: bind
        source: /DATA/AppData/beancount/bak
        target: /app/bak
      - type: bind
        source: /DATA/AppData/beancount/logs
        target: /app/logs

x-casaos:
  architectures:
    - arm64
    - amd64
  main: beancount-gs
  store_app_id: beancount-gs
  author: Cp0204
  category: Finance
  description:
    en_us: This project provides a RESTful API service (including front-end pages) for personal accounting and financial management based on beancount.Beancount is an excellent open-source double-entry bookkeeping tool. Because it is based on text recording, it is difficult to extend to the mobile terminal. This project aims to encapsulate common accounting behaviors into RESTful API.
    zh_cn: 本项目基于 beancount 提供个人记账财务管理的 RESTful API 服务（包含前端页面）。beancount 是一个优秀的开源复式记账工具，因为其基于文本记录的特性，难以拓展到移动端；本项目旨在将常见的记账行为封装为 RESTful API。
  developer: xdbin
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/beancount-gs/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/beancount-gs/screenshot-1.png
  tagline:
    en_us: A RESTful API service for personal accounting and financial management based on beancount.
    zh_cn: 基于 beancount 的个人记账财务管理 RESTful API 服务。
  title:
    en_us: beancount-gs
  port_map: "10000"
