name: orion-visor
services:
  orion-visor:
    image: registry.cn-hangzhou.aliyuncs.com/orionsec/orion-visor-service:2.2.2
    privileged: true
    ports:
      - 1081:80
    environment:
      MYSQL_HOST: orion-visor-mysql
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: orion_visor
      MYSQL_USER: root
      MYSQL_PASSWORD: Data@123456
      REDIS_HOST: orion-visor-redis
      REDIS_PASSWORD: Data@123456
      SECRET_KEY: uQeacXV8b3isvKLK
      DEMO_MODE: 'false'
    volumes:
      - /DATA/AppData/orion-visor/service/root-orion:/root/orion
    healthcheck:
      test: [ "CMD", "curl", "http://127.0.0.1:9200/orion-visor/api/server/bootstrap/health" ]
      interval: 15s
      timeout: 300s
      retries: 15
      start_period: 3s
    depends_on:
      orion-visor-mysql:
        condition: service_healthy
      orion-visor-redis:
        condition: service_healthy
    links:
      - orion-visor-mysql
      - orion-visor-redis
    restart: unless-stopped
    container_name: orion-visor
    deploy:
      resources:
        reservations:
          memory: 512M
    networks:
      - orion-visor

  orion-visor-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/orionsec/orion-visor-mysql:2.2.2
    privileged: true
    # ports:
    #   - 3307:3306
    environment:
      MYSQL_DATABASE: orion_visor
      MYSQL_USER: orion
      MYSQL_PASSWORD: Data@123456
      MYSQL_ROOT_PASSWORD: Data@123456
    volumes:
      - /DATA/AppData/orion-visor/mysql/var-lib-mysql:/var/lib/mysql
      - /DATA/AppData/orion-visor/mysql/var-lib-mysql-files:/var/lib/mysql-files
      - /DATA/AppData/orion-visor/mysql/etc-mysql:/etc/mysql
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306" ]
      interval: 15s
      timeout: 60s
      retries: 15
      start_period: 3s
    restart: unless-stopped
    container_name: orion-visor-mysql
    networks:
      - orion-visor

  orion-visor-redis:
    image: registry.cn-hangzhou.aliyuncs.com/orionsec/orion-visor-redis:2.2.2
    privileged: true
    # ports:
    #   - 6380:6379
    environment:
      REDIS_PASSWORD: Data@123456
    volumes:
      - /DATA/AppData/orion-visor/redis/data:/data
    command: sh -c "redis-server /usr/local/redis.conf --requirepass Data@123456"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 60s
      retries: 15
      start_period: 3s
    restart: unless-stopped
    container_name: orion-visor-redis
    networks:
      - orion-visor

networks:
  orion-visor:
    name: orion-visor

x-casaos:
  architectures:
    - amd64
  main: orion-visor
  author: Cp0204
  category: Utilities
  description:
    en_us: Orion Visor is a high-value, modern intelligent operation and maintenance & lightweight bastion platform. Orion-visor provides a one-stop server operation and maintenance solution.
    zh_cn: Orion Visor 是一款颜值高、体验好的开源轻量级堡垒机，致力于提高运维效率，解放双手。支持常见Linux系统，强大的Web终端，完善的WEB管理界面，开箱即用。
  developer: lijiahangmax
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/screenshot-4.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/screenshot-5.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/screenshot-6.png
  tagline:
    en_us: A high-value, modern intelligent operation and maintenance & lightweight bastion platform.
    zh_cn: 一款高颜值、现代化的智能运维&轻量堡垒机平台
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/orion-visor/thumbnail.png
  tips:
    before_install:
      en_us: |
        Wait for the backend service to start (≈2min) and visit
        Account: `admin`
        Password: `admin`
      zh_cn: |
        等待后端服务启动后 (≈2min) 访问
        账号: `admin`
        密码: `admin`
  title:
    en_us: Orion Visor
  index: /
  port_map: "1081"
